import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import prettierConfig from "eslint-config-prettier/flat";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

/**
 * Layer boundaries, enforced by lint rather than by convention.
 *
 * PROJECT_STRUCTURE.md §7 defines which layer may import which. Conventions
 * decay under deadline pressure; a lint error does not. These rules are what
 * physically prevent "UI mixed with business logic" — a client component
 * cannot import `@/server`, so the mistake fails CI instead of shipping.
 *
 * Dependencies point inward:
 *   config  -> (nothing)
 *   lib     -> config
 *   ui      -> lib, config
 *   feature -> components, lib, config
 *   server  -> lib, config, feature schemas (the one sanctioned exception)
 *   app     -> everything
 */
const layerBoundaries = [
  {
    name: "config must not import from any other layer",
    files: ["src/config/**/*.{ts,tsx}"],
    forbidden: [
      {
        group: [
          "@/lib/*",
          "@/server/*",
          "@/features/*",
          "@/components/*",
          "@/app/*",
        ],
      },
    ],
  },
  {
    name: "lib may only import config",
    files: ["src/lib/**/*.{ts,tsx}"],
    forbidden: [
      { group: ["@/server/*", "@/features/*", "@/components/*", "@/app/*"] },
    ],
  },
  {
    name: "components may only import lib and config",
    files: ["src/components/**/*.{ts,tsx}"],
    forbidden: [{ group: ["@/server/*", "@/features/*", "@/app/*"] }],
  },
  {
    name: "features must not reach into server, app, or a sibling feature",
    // Same-feature imports use relative paths, so an `@/features/*` import
    // from inside a feature is always a cross-feature import.
    files: ["src/features/**/*.{ts,tsx}"],
    forbidden: [{ group: ["@/server/*", "@/app/*", "@/features/*"] }],
  },
  {
    name: "server must not import UI, but may import shared feature schemas",
    files: ["src/server/**/*.{ts,tsx}"],
    forbidden: [
      {
        group: [
          "@/components/*",
          "@/app/*",
          "@/features/*",
          // The one documented exception: schemas are pure Zod with no server
          // dependencies, and sharing them is what guarantees client and
          // server validate against identical rules.
          "!@/features/*/schemas",
          "!@/features/*/schemas/*",
        ],
      },
    ],
  },
];

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts",
    ],
  },

  ...layerBoundaries.map(({ name, files, forbidden }) => ({
    name,
    files,
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: forbidden.map((rule) => ({
            ...rule,
            message: `Layer violation: ${name}. See PROJECT_STRUCTURE.md section 7.`,
          })),
        },
      ],
    },
  })),

  // CLAUDE.md R6: `lib/env.ts` is the only module permitted to read
  // process.env. Everything else imports validated, typed values, so a
  // missing variable fails at boot with a readable message rather than
  // surfacing as `undefined` deep inside a request handler.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/env.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.name='process'][property.name='env']",
          message:
            "Read environment variables through @/lib/env instead of process.env directly (CLAUDE.md R6).",
        },
      ],
    },
  },

  // shadcn/ui primitives are vendor code, regenerated by the CLI. Hand-edits
  // are lost, so lint findings there are not ours to fix.
  {
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

  // Must come last: disables stylistic rules that would fight Prettier.
  prettierConfig,
];

export default eslintConfig;
