import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { AppChrome } from "@/app/_components/AppChrome";
import { CodeBlock } from "@/components/shared/CodeBlock";
import { Container } from "@/components/shared/Container";
import { PageHeader } from "@/components/shared/PageHeader";
import { SectionCard } from "@/components/shared/SectionCard";
import { Button } from "@/components/ui/button";
import { FileCode2 } from "lucide-react";
import { demos, getDemo } from "@/features/demo/lib/demos";
import { ReportView } from "@/features/review/components/ReportView";

/** Pre-renders every demo at build time — they never change at runtime. */
export function generateStaticParams() {
  return demos.map((demo) => ({ slug: demo.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const demo = getDemo((await params).slug);

  if (!demo) return { title: "Example not found" };

  return {
    title: `${demo.title} — Example review`,
    description: demo.blurb,
  };
}

export default async function DemoPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const demo = getDemo((await params).slug);

  if (!demo) notFound();

  return (
    <AppChrome>
      <Container className="max-w-4xl space-y-8 py-10">
        <div>
          <Button asChild variant="ghost" size="sm" className="mb-4 -ml-2">
            <Link href="/demo">
              <ArrowLeft aria-hidden="true" />
              All examples
            </Link>
          </Button>

          <PageHeader
            title={demo.title}
            description="A real review, generated by DevLens AI and saved as an example."
            actions={
              <Button asChild>
                <Link href="/review/new">Review your own code</Link>
              </Button>
            }
          />
        </div>

        {/* The reviewed source is shown first — a review is meaningless
            without the code it refers to, and the findings cite line
            numbers. */}
        <SectionCard title="The code under review" icon={FileCode2}>
          <CodeBlock code={demo.sourceCode} />
        </SectionCard>

        <ReportView result={demo.result} />
      </Container>
    </AppChrome>
  );
}
