import "server-only";

import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { nextCookies } from "better-auth/next-js";

import { db } from "@/lib/db";
import { getServerEnv } from "@/lib/env";

/**
 * Better Auth configuration — the single source of truth for authentication.
 *
 * Two providers are enabled: email/password and Google. Both are free, which
 * the zero-cost constraint requires.
 *
 * The `user`, `session`, `account` and `verification` tables backing this are
 * generated by the Better Auth CLI and are never hand-edited (CLAUDE.md §8).
 * Our own settings live in the separate `UserPreference` table so that our
 * schema is not coupled to their code generation.
 */

const env = getServerEnv();

/**
 * Origins Better Auth will accept requests from.
 *
 * Vercel serves the same deployment from several hostnames — the production
 * alias, a branch alias, and a unique per-deployment URL. `BETTER_AUTH_URL`
 * can only name one of them, so visiting any other host fails with
 * "invalid origin", which reads as a broken login rather than a
 * configuration mismatch.
 *
 * Vercel supplies these values without a scheme, so https:// is prefixed.
 * They are environment-injected and cannot be spoofed by a client, so
 * trusting them does not widen the attack surface.
 */
const trustedOrigins = [
  env.BETTER_AUTH_URL,
  env.VERCEL_URL,
  env.VERCEL_BRANCH_URL,
  env.VERCEL_PROJECT_PRODUCTION_URL,
]
  .filter((value): value is string => Boolean(value))
  .map((value) => (value.startsWith("http") ? value : `https://${value}`))
  // De-duplicate: BETTER_AUTH_URL usually equals the production alias.
  .filter((value, index, all) => all.indexOf(value) === index);

export const auth = betterAuth({
  trustedOrigins,

  database: prismaAdapter(db, {
    provider: "postgresql",
  }),

  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,

  emailAndPassword: {
    enabled: true,
    // Verification requires an email provider, which would mean a paid
    // service or another external dependency. Deferred deliberately —
    // see IMPLEMENTATION_ROADMAP.md. Password rules are enforced by the
    // shared Zod schemas so client and server agree.
    requireEmailVerification: false,
    minPasswordLength: 8,
    maxPasswordLength: 128,
  },

  socialProviders: {
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    },
  },

  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // refresh at most once a day
  },

  databaseHooks: {
    user: {
      create: {
        // Every user gets a preferences row at sign-up, so no later code has
        // to handle "preferences might not exist yet". Failing here must not
        // fail the sign-up itself — an account without preferences is
        // recoverable (the repository upserts defaults); a failed
        // registration is not.
        after: async (user) => {
          try {
            await db.userPreference.create({ data: { userId: user.id } });
          } catch {
            // Non-fatal by design; preference.repository.findOrCreate
            // backfills on first read.
          }
        },
      },
    },
  },

  advanced: {
    // Cookies are readable only by the server and sent over HTTPS in
    // production. `sameSite: lax` still permits the OAuth redirect back from
    // Google, which `strict` would block.
    defaultCookieAttributes: {
      httpOnly: true,
      sameSite: "lax",
    },
  },

  // Must be last: lets Better Auth set cookies from Next.js server actions
  // and route handlers.
  plugins: [nextCookies()],
});

export type Session = typeof auth.$Infer.Session;
export type SessionUser = Session["user"];
