import { LANGUAGE_CONFIGS } from "@/config/languages";
import type {
  Finding,
  ReviewResult,
  Suggestion,
} from "@/features/review/schemas/review-result.schema";

/**
 * Serialise a review to Markdown.
 *
 * A pure function with no dependencies on React, the DOM or the database, so
 * it can be unit tested directly and reused by the download route, the copy
 * button, and any future GitHub-comment integration. Written once, tested
 * once.
 */

export interface MarkdownReviewMeta {
  title: string;
  language: string;
  createdAt: Date | string;
  overallScore: number | null;
}

/**
 * Escape a value that will sit inside a fenced code block.
 *
 * Model output can itself contain triple backticks — a refactor that includes
 * a Markdown example, for instance. Without this the fence closes early and
 * the rest of the document renders as prose.
 */
function fence(code: string, language = ""): string {
  const longestRun = [...code.matchAll(/`+/g)].reduce(
    (longest, match) => Math.max(longest, match[0].length),
    0,
  );

  // A fence must be longer than any backtick run it contains.
  const ticks = "`".repeat(Math.max(3, longestRun + 1));

  return `${ticks}${language}\n${code}\n${ticks}`;
}

/** Escape pipes so a value cannot break out of a Markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

function findingsSection(title: string, findings: Finding[]): string {
  if (findings.length === 0) {
    return `## ${title}\n\nNone found.\n`;
  }

  const body = findings
    .map((finding) => {
      const location = finding.line > 0 ? ` _(line ${finding.line})_` : "";
      return [
        `### ${finding.severity} — ${finding.title}${location}`,
        "",
        finding.description,
        "",
        `**Fix:** ${finding.suggestion}`,
      ].join("\n");
    })
    .join("\n\n");

  return `## ${title}\n\n${body}\n`;
}

function suggestionsSection(title: string, suggestions: Suggestion[]): string {
  if (suggestions.length === 0) {
    return `## ${title}\n\nNone.\n`;
  }

  const body = suggestions
    .map(
      (suggestion) =>
        `- **${suggestion.title}** (${suggestion.impact} impact) — ${suggestion.description}`,
    )
    .join("\n");

  return `## ${title}\n\n${body}\n`;
}

export function toMarkdown(
  result: ReviewResult,
  meta: MarkdownReviewMeta,
): string {
  const languageLabel =
    LANGUAGE_CONFIGS.find((config) => config.value === meta.language)?.label ??
    meta.language;

  const created =
    meta.createdAt instanceof Date ? meta.createdAt : new Date(meta.createdAt);

  const sections = [
    `# ${meta.title}`,
    "",
    `| | |`,
    `| --- | --- |`,
    `| **Score** | ${result.overallScore}/100 |`,
    `| **Language** | ${cell(languageLabel)} |`,
    `| **Reviewed** | ${created.toISOString().slice(0, 10)} |`,
    "",
    "## Summary",
    "",
    result.summary,
    "",
    findingsSection("Bugs", result.bugs),
    findingsSection("Security", result.securityIssues),
    findingsSection("Performance", result.performanceIssues),
    findingsSection("Code smells", result.codeSmells),
    suggestionsSection("Maintainability", result.maintainability),
    suggestionsSection("Best practices", result.bestPractices),
    "## Complexity",
    "",
    `- **Time:** ${result.timeComplexity.value} — ${result.timeComplexity.explanation}`,
    `- **Space:** ${result.spaceComplexity.value} — ${result.spaceComplexity.explanation}`,
    "",
  ];

  // Omitted entirely when the user disabled the refactor, rather than left as
  // an empty heading.
  if (result.refactoredCode.trim()) {
    sections.push(
      "## Refactored code",
      "",
      "> Generated code is a suggestion, not verified output. Review before use.",
      "",
      fence(result.refactoredCode, meta.language.toLowerCase()),
      "",
    );
  }

  sections.push(
    "## Commit message",
    "",
    fence(result.commitMessage),
    "",
    "## Pull request description",
    "",
    result.prDescription,
    "",
    "---",
    "",
    "_Generated by DevLens AI._",
  );

  return sections.join("\n");
}

/** Filename for a downloaded review. Safe on every filesystem. */
export function markdownFilename(
  title: string,
  createdAt: Date | string,
): string {
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "review";

  const date = (createdAt instanceof Date ? createdAt : new Date(createdAt))
    .toISOString()
    .slice(0, 10);

  return `devlens-${slug}-${date}.md`;
}
